name: One-Click Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      customer:
        description: 'Customer ID'
        required: true
        default: 'demo-customer'
      region:
        description: 'AWS Region'
        required: true
        default: 'us-east-1'
      size:
        description: 'Deployment size'
        required: true
        default: 'small'

env:
  TF_VERSION: '1.5.0'
  WORKING_DIR: 'infra/envs/dev'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Format Check
        run: terraform fmt -check -recursive
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ env.WORKING_DIR }}

  plan:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform Plan
        run: |
          terraform plan \
            -var="customer_id=${{ github.run_id }}" \
            -var="region=${{ github.event.inputs.region || 'us-east-1' }}" \
            -var="size=${{ github.event.inputs.size || 'small' }}" \
            -lock=false
        working-directory: ${{ env.WORKING_DIR }}

  deploy:
    runs-on: ubuntu-latest
    needs: plan
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Infrastructure (Dry Run)
        run: ./scripts/deploy_infrastructure.sh
        env:
          CUSTOMER_ID: ${{ github.event.inputs.customer || github.run_id }}
          REGION: ${{ github.event.inputs.region || 'us-east-1' }}
          SIZE: ${{ github.event.inputs.size || 'small' }}

      - name: Configure DNS (Dry Run)
        run: ./scripts/configure_dns.sh
        env:
          CUSTOMER_ID: ${{ github.event.inputs.customer || github.run_id }}
          REGION: ${{ github.event.inputs.region || 'us-east-1' }}

  test:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Smoke Tests
        run: ./scripts/run_smoke_checks.sh
        env:
          CUSTOMER_ID: ${{ github.event.inputs.customer || github.run_id }}
          REGION: ${{ github.event.inputs.region || 'us-east-1' }}
          SIZE: ${{ github.event.inputs.size || 'small' }}
